{{- if .Values.clickhouse.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "fnpc.fullname" . }}-clickhouse-admin
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "fnpc.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ include "fnpc.fullname" . }}-clickhouse-admin
    creationPolicy: Owner
  data:
    - secretKey: CLICKHOUSE_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.clickhouse.admin.onepasswordItem }}
        property: {{ .Values.clickhouse.admin.passwordProperty }}
{{- end }}
