{{- if .Values.clickhouse.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.clickhouse.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "fnpc.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Values.clickhouse.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.onepassword.clickhouseItem }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.onepassword.clickhouseItem }}
        property: password
{{- end }}
